import { db } from '../config/database';
import { logger } from '../config/logger';
import { eventBus, AppEvent } from './event-bus';
import { notify } from './notification-engine';

interface Condition {
  field: string;
  operator: string;
  value: unknown;
}

interface ConditionGroup {
  logic: 'AND' | 'OR';
  conditions: (Condition | ConditionGroup)[];
}

interface Action {
  type: string;
  config: Record<string, unknown>;
}

function evaluateCondition(record: Record<string, unknown>, condition: Condition): boolean {
  const fieldValue = record[condition.field];
  const targetValue = condition.value;

  switch (condition.operator) {
    case 'equals': return String(fieldValue) === String(targetValue);
    case 'not_equals': return String(fieldValue) !== String(targetValue);
    case 'greater_than': return Number(fieldValue) > Number(targetValue);
    case 'less_than': return Number(fieldValue) < Number(targetValue);
    case 'contains': return String(fieldValue).toLowerCase().includes(String(targetValue).toLowerCase());
    case 'in': return Array.isArray(targetValue) && targetValue.includes(fieldValue);
    case 'is_empty': return !fieldValue || fieldValue === '';
    case 'is_not_empty': return !!fieldValue && fieldValue !== '';
    case 'regex': return new RegExp(String(targetValue)).test(String(fieldValue));
    default: return false;
  }
}

function evaluateConditions(record: Record<string, unknown>, group: ConditionGroup): boolean {
  if (!group.conditions || group.conditions.length === 0) return true;

  const results = group.conditions.map((c) => {
    if ('logic' in c) return evaluateConditions(record, c as ConditionGroup);
    return evaluateCondition(record, c as Condition);
  });

  return group.logic === 'AND' ? results.every(Boolean) : results.some(Boolean);
}

async function executeAction(
  tableName: string,
  recordId: string,
  record: Record<string, unknown>,
  action: Action,
  userId: string,
): Promise<void> {
  switch (action.type) {
    case 'set_field':
      await db(tableName).where('id', recordId).update({
        [action.config.field as string]: action.config.value,
        updated_at: new Date(),
      });
      break;

    case 'change_state':
      await db(tableName).where('id', recordId).update({
        state: action.config.state,
        updated_at: new Date(),
      });
      break;

    case 'assign_to':
      await db(tableName).where('id', recordId).update({
        assigned_to: action.config.user_id,
        updated_at: new Date(),
      });
      break;

    case 'assign_to_group':
      await db(tableName).where('id', recordId).update({
        assignment_group_id: action.config.group_id,
        updated_at: new Date(),
      });
      break;

    case 'send_notification':
      if (record.assigned_to) {
        await notify(
          record.assigned_to as string,
          action.config.title as string || 'Workflow Notification',
          action.config.body as string || `Workflow triggered on ${record.number || recordId}`,
          action.config.link as string,
        );
      }
      break;

    case 'create_journal_entry':
      await db('sys_journal').insert({
        table_name: tableName,
        record_id: recordId,
        type: action.config.journal_type || 'work_note',
        body: action.config.body || 'Auto-generated by workflow',
        created_by: userId,
      });
      break;

    default:
      logger.warn(`Unknown workflow action type: ${action.type}`);
  }
}

async function processEvent(event: AppEvent): Promise<void> {
  try {
    const rules = await db('workflow_rules')
      .where({ table_name: event.tableName, trigger_event: event.type, active: true })
      .orderBy('execution_order', 'asc');

    for (const rule of rules) {
      const conditions = rule.conditions as ConditionGroup;
      const match = evaluateConditions(event.data, conditions);

      if (match) {
        const actions = rule.actions as Action[];
        let status = 'success';
        let error: string | null = null;

        try {
          for (const action of actions) {
            await executeAction(event.tableName, event.recordId, event.data, action, event.userId);
          }
        } catch (err: any) {
          status = 'error';
          error = err.message;
          logger.error(`Workflow action failed: ${rule.name}`, err);
        }

        await db('workflow_executions').insert({
          rule_id: rule.id,
          table_name: event.tableName,
          record_id: event.recordId,
          status,
          error,
        });
      }
    }
  } catch (err) {
    logger.error('Workflow engine error', err);
  }
}

export function initWorkflowEngine(): void {
  eventBus.on('record.created', processEvent);
  eventBus.on('record.updated', processEvent);
  eventBus.on('record.state_changed', processEvent);
  logger.info('Workflow engine initialized');
}
