import { z } from 'zod';

export const createReleaseSchema = z.object({
  short_description: z.string().min(1).max(200),
  description: z.string().max(10000).optional(),
  release_type: z.enum(['major', 'minor', 'patch', 'hotfix']).optional(),
  risk: z.enum(['high', 'moderate', 'low']).optional(),
  impact: z.enum(['high', 'moderate', 'low']).optional(),
  priority: z.number().int().min(1).max(5).optional(),
  release_manager_id: z.string().uuid().optional().nullable(),
  assigned_to: z.string().uuid().optional().nullable(),
  assignment_group_id: z.string().uuid().optional().nullable(),
  scheduled_start: z.string().optional().nullable(),
  scheduled_end: z.string().optional().nullable(),
  implementation_plan: z.string().optional().nullable(),
  test_plan: z.string().optional().nullable(),
  rollback_plan: z.string().optional().nullable(),
  communication_plan: z.string().optional().nullable(),
  deployed_version: z.string().max(100).optional().nullable(),
  previous_version: z.string().max(100).optional().nullable(),
  build_number: z.string().max(100).optional().nullable(),
});

export const updateReleaseSchema = z.object({
  short_description: z.string().min(1).max(200).optional(),
  description: z.string().max(10000).optional(),
  state: z.string().optional(),
  release_type: z.enum(['major', 'minor', 'patch', 'hotfix']).optional(),
  risk: z.enum(['high', 'moderate', 'low']).optional(),
  impact: z.enum(['high', 'moderate', 'low']).optional(),
  priority: z.number().int().min(1).max(5).optional(),
  release_manager_id: z.string().uuid().optional().nullable(),
  assigned_to: z.string().uuid().optional().nullable(),
  assignment_group_id: z.string().uuid().optional().nullable(),
  scheduled_start: z.string().optional().nullable(),
  scheduled_end: z.string().optional().nullable(),
  actual_start: z.string().optional().nullable(),
  actual_end: z.string().optional().nullable(),
  implementation_plan: z.string().optional().nullable(),
  test_plan: z.string().optional().nullable(),
  rollback_plan: z.string().optional().nullable(),
  communication_plan: z.string().optional().nullable(),
  deployed_version: z.string().max(100).optional().nullable(),
  previous_version: z.string().max(100).optional().nullable(),
  build_number: z.string().max(100).optional().nullable(),
});
